import { SportEvent } from '@/types';

export const mockEvents: SportEvent[] = [
  // Football - Today
  {
    id: 'epl-1',
    sport: 'football',
    homeTeam: 'Manchester City',
    awayTeam: 'Chelsea',
    date: new Date(new Date().setHours(15, 0, 0, 0)),
    time: '3:00 PM COT',
    league: 'Premier League',
    status: 'scheduled',
  },
  {
    id: 'laliga-1',
    sport: 'football',
    homeTeam: 'Real Madrid',
    awayTeam: 'Barcelona',
    date: new Date(new Date().setHours(20, 0, 0, 0)),
    time: '8:00 PM COT',
    league: 'La Liga',
    status: 'scheduled',
  },
  {
    id: 'ucl-1',
    sport: 'football',
    homeTeam: 'Bayern Munich',
    awayTeam: 'PSG',
    date: new Date(new Date().setHours(18, 45, 0, 0)),
    time: '6:45 PM COT',
    league: 'UEFA Champions League',
    status: 'scheduled',
  },
  {
    id: 'arg-1',
    sport: 'football',
    homeTeam: 'River Plate',
    awayTeam: 'Boca Juniors',
    date: new Date(new Date().setHours(19, 0, 0, 0)),
    time: '7:00 PM COT',
    league: 'Liga Profesional Argentina',
    status: 'scheduled',
  },
  {
    id: 'atp-1',
    sport: 'tennis',
    homeTeam: 'Jannik Sinner',
    awayTeam: 'Novak Djokovic',
    date: new Date(new Date().setHours(12, 0, 0, 0)),
    time: '12:00 PM COT',
    league: 'ATP Masters 1000',
    status: 'scheduled',
  },
  {
    id: 'f1-1',
    sport: 'formula1',
    homeTeam: 'Max Verstappen',
    awayTeam: 'Lewis Hamilton',
    date: new Date(new Date().setHours(14, 0, 0, 0)),
    time: '2:00 PM COT',
    league: 'Formula 1 - Australian GP',
    status: 'scheduled',
  },
  {
    id: 'epl-2',
    sport: 'football',
    homeTeam: 'Liverpool',
    awayTeam: 'Manchester United',
    date: new Date(new Date().setDate(new Date().getDate() + 1)),
    time: '3:00 PM COT',
    league: 'Premier League',
    status: 'scheduled',
  },
  {
    id: 'uel-1',
    sport: 'football',
    homeTeam: 'AS Roma',
    awayTeam: 'Sevilla',
    date: new Date(new Date().setDate(new Date().getDate() + 1)),
    time: '7:00 PM COT',
    league: 'UEFA Europa League',
    status: 'scheduled',
  },
  {
    id: 'wc26-1',
    sport: 'football',
    homeTeam: 'Argentina',
    awayTeam: 'Brazil',
    date: new Date(new Date().setDate(new Date().getDate() + 3)),
    time: '7:30 PM COT',
    league: 'FIFA World Cup 2026 Qualifiers',
    status: 'scheduled',
  },
  {
    id: 'atp-2',
    sport: 'tennis',
    homeTeam: 'Carlos Alcaraz',
    awayTeam: 'Daniil Medvedev',
    date: new Date(new Date().setDate(new Date().getDate() + 2)),
    time: '2:00 PM COT',
    league: 'ATP 500',
    status: 'scheduled',
  },
  {
    id: 'f1-2',
    sport: 'formula1',
    homeTeam: 'Lando Norris',
    awayTeam: 'Oscar Piastri',
    date: new Date(new Date().setDate(new Date().getDate() + 5)),
    time: '3:00 AM COT',
    league: 'Formula 1 - Malaysian GP',
    status: 'scheduled',
  },
  {
    id: 'laliga-2',
    sport: 'football',
    homeTeam: 'Atletico Madrid',
    awayTeam: 'Valencia',
    date: new Date(new Date().setDate(new Date().getDate() + 7)),
    time: '4:00 PM COT',
    league: 'La Liga',
    status: 'scheduled',
  },
];
